enum SetupDefination
{	                    //Access Level	,Default		,Description														,Chinese
	//MODULE_ID_0 System
	SET_SYCycleUPH,		//3				,20				,Cycle rate calculation for UPH										,
	
	SET_SYCHKPREPO,		//4				,1				,Yield calculation layout position(0 - 19)							,
	SET_SYNXCYLBRK,		//4				,1000			,Cycle(s) before re-display low yield warning						,
	SET_SYBRKTOLOW,		//4				,96				,General low yield threshold(%)										,
	SET_SYVITOLOW1,		//4				,90				,Vision 1 low yield threshold(%)									,
	SET_SYVITOLOW2,		//4				,90				,Vision 2 low yield threshold(%)									,
	SET_SYVITOLOW3,		//4				,90				,Vision 3 low yield threshold(%)									,
	//SET_YITESTOLOW,		//4				,90				,Test 1 low yield threshold(%)										,

	SET_SYENDCOM11,		//9				,5				,Comm 1 end of receive line 1										,
	SET_SYENDCOM21,		//9				,6				,Comm 1 end of receive line 2										,
	SET_SYENDCOM31,		//9				,3				,Comm 1 end of receive line 3										,

	SET_SYENDCOM12,		//9				,13				,Comm 2 end of receive line 1										,
	SET_SYENDCOM22,		//9				,6				,Comm 2 end of receive line 2										,
	SET_SYENDCOM32,		//9				,3				,Comm 2 end of receive line 3										,

	SET_SYENDCOM13,		//9				,13				,Comm 3 end of receive line 1										,
	SET_SYENDCOM23,		//9				,6				,Comm 3 end of receive line 2										,
	SET_SYENDCOM33,		//9				,3				,Comm 3 end of receive line 3										,

	//MODULE_ID_1 Turret
	SET_TUDPERPOS1,		//4				,32				,Voice coil down position error reject position 			,
	SET_TUSPEEDSTO,		//4				,5				,cycle(s) to speed up from breakdown							,
	SET_TUCLEANING,		//4				,40				,purging cycle(s)											,
	SET_TUSPEEDSET,		//9				,8				,maximum speed (1-8)											,
	SET_TUMTNSPEED,		//4				,1				,speed for maintenance mode (1->2)							,
	SET_TUVCSCANL1,		//9				,0				,Voice coil enable tweak mode value(0=>Disable)						,
	SET_TUVCOPNRAM,		//9				,50				,Voice coil open loop ramp value									,
	
	SET_TUFORTRESH,		//9				,2000			,VC force activation threshold(um)(All)								,
	SET_TUDPTRESHO,		//9				,150			,VC DP detection threshold(um)(All)									,
	SET_TUUPTRESHO,		//9				,800			,VC up position threshold(um)(All)								,
	SET_TUEDTRESHO,		//9				,0				,VC early down threshold(deg)(All)								,
	SET_TUSOFTDIS1,		//4				,250			,VC soft landing default distance(All)									,
	SET_TUSOFTDUR1,		//4				,5				,VC soft landing default duration(All)									,
	//SET_TUDYNFORC1,		//4				,500			,VC maximum dynamic force(gram)(All)											,
	SET_TUTEAFORC1,		//4				,500			,VC maximum auto teach work force(gram)(All)											,
	SET_TUTEARSTF1,		//4				,300			,VC maximum auto teach rest force(gram)(All)											,

	SET_VCDYNFOR01,		//4				,500			,maximum dynamic force(gram)											,
	SET_VCDYNFOR02,		//4				,500			,maximum dynamic force(gram)											,
	SET_VCDYNFOR03,		//4				,500			,maximum dynamic force(gram)											,
	SET_VCDYNFOR04,		//4				,500			,maximum dynamic force(gram)											,
	SET_VCDYNFOR05,		//4				,500			,maximum dynamic force(gram)											,
	SET_VCDYNFOR06,		//4				,500			,maximum dynamic force(gram)											,
	SET_VCDYNFOR07,		//4				,500			,maximum dynamic force(gram)											,
	SET_VCDYNFOR08,		//4				,500			,maximum dynamic force(gram)											,
	SET_VCDYNFOR09,		//4				,500			,maximum dynamic force(gram)											,
	SET_VCDYNFOR10,		//4				,500			,maximum dynamic force(gram)											,
	SET_VCDYNFOR11,		//4				,500			,maximum dynamic force(gram)											,
	SET_VCDYNFOR12,		//4				,500			,maximum dynamic force(gram)											,
	SET_VCDYNFOR13,		//4				,500			,maximum dynamic force(gram)											,
	SET_VCDYNFOR14,		//4				,500			,maximum dynamic force(gram)											,
	SET_VCDYNFOR15,		//4				,500			,maximum dynamic force(gram)											,
	SET_VCDYNFOR16,		//4				,500			,maximum dynamic force(gram)											,
	SET_VCDYNFOR17,		//4				,500			,maximum dynamic force(gram)											,
	SET_VCDYNFOR18,		//4				,500			,maximum dynamic force(gram)											,
	SET_VCDYNFOR19,		//4				,500			,maximum dynamic force(gram)											,
	SET_VCDYNFOR20,		//4				,500			,maximum dynamic force(gram)											,

	TEA_VCWORKP101,		//9				,2000			,work position(um)    						,
	TEA_VCWORKP102,		//9				,2000			,work position(um)    					,
	TEA_VCWORKP103,		//9				,2000			,work position(um)    						,
	TEA_VCWORKP104,		//9				,2000			,work position(um)    			,
	TEA_VCWORKP105,		//9				,2000			,work position(um)    			,
	TEA_VCWORKP106,		//9				,2000			,work position(um)    						,
	TEA_VCWORKP107,		//9				,2000			,work position(um)    						,
	TEA_VCWORKP108,		//9				,2000			,work position(um)    								,
	TEA_VCWORKP109,		//9				,2000			,work position(um) 								,
	TEA_VCWORKP110,		//9				,2000			,work position(um)						,
	TEA_VCWORKP111,		//9				,2000			,work position(um)				,
	TEA_VCWORKP112,		//9				,2000			,work position(um)						,
	TEA_VCWORKP113,		//9				,2000			,work position(um)				,
	TEA_VCWORKP114,		//9				,2000			,work position(um)						,
	TEA_VCWORKP115,		//9				,2000			,work position(um)				,
	TEA_VCWORKP116,		//9				,2000			,work position(um)				,
	TEA_VCWORKP117,		//9				,2000			,work position(um)				,
	TEA_VCWORKP118,		//9				,2000			,work position(um)				,
	TEA_VCWORKP119,		//9				,2000			,work position(um)				,
	TEA_VCWORKP120,		//9				,2000			,work position(um)				,

	TEA_VCRESTP101,		//4				,100			,rest position 			,
	TEA_VCRESTP102,		//4				,100			,rest position 		,
	TEA_VCRESTP103,		//4				,100			,rest position 				,
	TEA_VCRESTP104,		//4				,100			,rest position 			,
	TEA_VCRESTP105,		//4				,100			,rest position 			,
	TEA_VCRESTP106,		//4				,100			,rest position 						,
	TEA_VCRESTP107,		//4				,100			,rest position 					,
	TEA_VCRESTP108,		//4				,100			,rest position 						,
	TEA_VCRESTP109,		//4				,100			,rest position 					,
	TEA_VCRESTP110,		//4				,100			,rest position			,
	TEA_VCRESTP111,		//4				,100			,rest position			,
	TEA_VCRESTP112,		//4				,100			,rest position			,
	TEA_VCRESTP113,		//4				,100			,rest position			,
	TEA_VCRESTP114,		//4				,100			,rest position			,
	TEA_VCRESTP115,		//4				,100			,rest position			,
	TEA_VCRESTP116,		//4				,100			,rest position			,
	TEA_VCRESTP117,		//4				,100			,rest position			,
	TEA_VCRESTP118,		//4				,100			,rest position			,
	TEA_VCRESTP119,		//4				,100			,rest position			,
	TEA_VCRESTP120,		//4				,100			,rest position			,

	SET_VCSOFTLA01,		//4				,0			,soft landing stroke(%) 						,
	SET_VCSOFTLA02,		//4				,0			,soft landing stroke(%) 						,
	SET_VCSOFTLA03,		//4				,0			,soft landing stroke(%) 								,
	SET_VCSOFTLA04,		//4				,0			,soft landing stroke(%) 						,
	SET_VCSOFTLA05,		//4				,0			,soft landing stroke(%) 						,
	SET_VCSOFTLA06,		//4				,0			,soft landing stroke(%) 									,
	SET_VCSOFTLA07,		//4				,0			,soft landing stroke(%) 							,
	SET_VCSOFTLA08,		//4				,0			,soft landing stroke(%) 											,
	SET_VCSOFTLA09,		//4				,0			,soft landing stroke(%) 								,
	SET_VCSOFTLA10,		//4				,0			,soft landing stroke(%)							,
	SET_VCSOFTLA11,		//4				,0			,soft landing stroke(%)					,
	SET_VCSOFTLA12,		//4				,0			,soft landing stroke(%)							,
	SET_VCSOFTLA13,		//4				,0			,soft landing stroke(%)					,
	SET_VCSOFTLA14,		//4				,0			,soft landing stroke(%)							,
	SET_VCSOFTLA15,		//4				,0			,soft landing stroke(%)					,
	SET_VCSOFTLA16,		//4				,0			,soft landing stroke(%)					,
	SET_VCSOFTLA17,		//4				,0			,soft landing stroke(%)					,
	SET_VCSOFTLA18,		//4				,0			,soft landing stroke(%)					,
	SET_VCSOFTLA19,		//4				,0			,soft landing stroke(%)					,
	SET_VCSOFTLA20,		//4				,0			,soft landing stroke(%)					,

	SET_VCCOMFOR01,		//4				,0			,compression force(gram) 			,
	SET_VCCOMFOR02,		//4				,0			,compression force(gram) 					,
	SET_VCCOMFOR03,		//4				,0			,compression force(gram) 						,
	SET_VCCOMFOR04,		//4				,0			,compression force(gram) 			,
	SET_VCCOMFOR05,		//4				,0			,compression force(gram) 			,
	SET_VCCOMFOR06,		//4				,0			,compression force(gram) 						,
	SET_VCCOMFOR07,		//4				,0			,compression force(gram) 						,
	SET_VCCOMFOR08,		//4				,0			,compression force(gram) 								,
	SET_VCCOMFOR09,		//4				,0			,compression force(gram) 							,
	SET_VCCOMFOR10,		//4				,0			,compression force(gram)						,
	SET_VCCOMFOR11,		//4				,0			,compression force(gram)				,
	SET_VCCOMFOR12,		//4				,0			,compression force(gram)						,
	SET_VCCOMFOR13,		//4				,0			,compression force(gram)				,
	SET_VCCOMFOR14,		//4				,0			,compression force(gram)						,
	SET_VCCOMFOR15,		//4				,0			,compression force(gram)				,	
	SET_VCCOMFOR16,		//4				,0			,compression force(gram)				,	
	SET_VCCOMFOR17,		//4				,0			,compression force(gram)				,	
	SET_VCCOMFOR18,		//4				,0			,compression force(gram)				,	
	SET_VCCOMFOR19,		//4				,0			,compression force(gram)				,	
	SET_VCCOMFOR20,		//4				,0			,compression force(gram)				,	

	SET_VCMODGAP01,		//4				,250			,Gap between module for auto teach(um) 				,
	SET_VCMODGAP02,		//4				,250			,Gap between module for auto teach(um) 		,
	SET_VCMODGAP03,		//4				,0				,Gap between module for auto teach(um) 					,
	SET_VCMODGAP04,		//4				,0				,Gap between module for auto teach(um) 					,
	SET_VCMODGAP05,		//4				,250			,Gap between module for auto teach(um) 					,
	SET_VCMODGAP06,		//4				,250			,Gap between module for auto teach(um) 						,
	SET_VCMODGAP07,		//4				,250			,Gap between module for auto teach(um) 					,
	SET_VCMODGAP08,		//4				,250			,Gap between module for auto teach(um) 					,
	SET_VCMODGAP09,		//4				,250			,Gap between module for auto teach(um) 				,
	SET_VCMODGAP10,		//4				,250			,Gap between module for auto teach(um)			,
	SET_VCMODGAP11,		//4				,250			,Gap between module for auto teach(um)				,
	SET_VCMODGAP12,		//4				,250			,Gap between module for auto teach(um)			,
	SET_VCMODGAP13,		//4				,250			,Gap between module for auto teach(um)				,
	SET_VCMODGAP14,		//4				,250			,Gap between module for auto teach(um)			,
	SET_VCMODGAP15,		//4				,250			,Gap between module for auto teach(um)				,
	SET_VCMODGAP16,		//4				,250			,Gap between module for auto teach(um)				,
	SET_VCMODGAP17,		//4				,250			,Gap between module for auto teach(um)				,
	SET_VCMODGAP18,		//4				,250			,Gap between module for auto teach(um)				,
	SET_VCMODGAP19,		//4				,250			,Gap between module for auto teach(um)				,
	SET_VCMODGAP20,		//4				,250			,Gap between module for auto teach(um)				,
	
	SET_TUDEFDURAT,		//4				,20				,Turret Movement Default Duration (ms)								,
	SET_TUVCDEFDUR,		//4				,5				,VC Movement Default Duration (ms)									,
	SET_TURESTDIST,		//4				,2500			,VC move to rest default distance(ms)									,
	SET_TURESTDURA,		//4				,5				,VC move to rest default duration(ms)									,

	//MODULE_ID_2 Rotary 1
	SET_RODISTANC1,		//9				,90000			,motor movement distance										,
	SET_RODURATIO1,		//4				,15				,motor movement duration								,
	SET_ROTHET0001,		//4				,0				,orientation '0' theta angle (0 - 359999)										,
	SET_ROTHET0101,		//4				,90000			,orientation '1' theta angle (0 - 359999)										,
	SET_ROTHET0201,		//4				,-90000			,orientation '2' theta angle (0 - 359999)									,
	SET_ROTHET0301,		//4				,180000			,orientation '3' theta angle (0 - 359999)									,
	SET_ROOFFD0001,		//4				,0				,orientation '0' theta offset before pickup										,
	SET_ROOFFD0101,		//4				,0				,orientation '1' theta offset before pickup										,
	SET_ROOFFD0201,		//4				,0				,orientation '2' theta offset before pickup									,
	SET_ROOFFD0301,		//4				,0				,orientation '3' theta offset before pickup									,
	TEA_ROPOSWORK1,		//4				,10				,work position												,
	SET_ROINTRETR1,		//4				,2				,retry before fail to initialise							, 
	SET_RORETRACT1,		//4				,0				,retract stroke											,
	SET_ROROTREC01,		//4				,4				,recenter unit rotate mode:0)0 1)+90 2)-90 3)180	,
	SET_ROLIMBYP01,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_ROREJDP001,		//4				,32				,down position error unit reject position (0 - 19)	, 

	//MODULE_ID_3 Rotary 2
	SET_RODISTANC2,		//9				,90000			,motor movement distance										,
	SET_RODURATIO2,		//4				,15				,motor movement duration								,
	SET_ROTHET0002,		//4				,0				,orientation '0' theta angle (0 - 359999)										,
	SET_ROTHET0102,		//4				,90000			,orientation '1' theta angle (0 - 359999)										,
	SET_ROTHET0202,		//4				,-90000			,orientation '2' theta angle (0 - 359999)									,
	SET_ROTHET0302,		//4				,180000			,orientation '3' theta angle (0 - 359999)									,
	SET_ROOFFD0002,		//4				,0				,orientation '0' theta offset before pickup											,
	SET_ROOFFD0102,		//4				,0				,orientation '1' theta offset before pickup										,
	SET_ROOFFD0202,		//4				,0				,orientation '2' theta offset before pickup									,
	SET_ROOFFD0302,		//4				,0				,orientation '3' theta offset before pickup									,
	TEA_ROPOSWORK2,		//4				,10				,work position												,
	SET_ROINTRETR2,		//4				,2				,retry before fail to initialise							, 
	SET_RORETRACT2,		//4				,0				,retract stroke						            ,
	SET_ROROTREC02,		//4				,4				,recenter unit rotate mode:0)0 1)+90 2)-90 3)180	,
	SET_ROLIMBYP02,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_ROREJDP002,		//4				,32				,down position error unit reject position (0 - 19)	, 

	//MODULE_ID_4 Recentering 1
	SET_RELIMBYP01,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_REREJDP001,		//4				,32				,down position error unit reject position (0 - 19)	, 

	//MODULE_ID_5 Recentering 2
	SET_RELIMBYP02,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_REREJDP002,		//4				,32				,down position error unit reject position (0 - 19)	, 

	//MODULE_ID_6 Recentering 3
	SET_RELIMBYP03,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_REREJDP003,		//4				,32				,down position error unit reject position (0 - 19)	, 

	//MODULE_ID_7 Recentering 4
	SET_RELIMBYP04,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_REREJDP004,		//4				,32				,down position error unit reject position (0 - 19)	, 

	//MODULE_ID_8 Feeding
	SET_FESEPRETRY,		//1				,10				,separator retry before breakdown								, 
	SET_FEDEADSPOT,		//2				,99				,dead spot error unit reject position(99 = disable)				,
	TEA_FETEACHFRN,		//2				,120000			,separator front position(encoder)								,
	TEA_FETEACHBCK,		//2				,120000			,separator back position(encoder)								,
	SET_FEDISTANC1,		//9				,60000			,motor movement distance										,
	SET_FEDURATIO1,		//4				,15				,motor movement duration										,
	SET_FEINTRETR1,		//4				,2				,retry before fail to initialise								, 	
	SET_FELIMBYP01,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_FEREJDP001,		//4				,32				,down position error unit reject position (0 - 19)	, 

	//MODULE_ID_9 Minitable
	TEA_TAPOSWORK1,		//4				,10				,working position(encoder)								,
	SET_TADISTANC1,		//9				,90000			,motor movement distance									,
	SET_TADURATIO1,		//4				,12				,motor movement duration									,
	SET_TASLODIST1,		//9				,10000			,slow motor movement distance								,
	SET_TASLODURA1,		//4				,30				,slow motor movement duration								,
	SET_TARETRACT1,		//4				,500			,PUH retract before motion cycle(um)						,
	SET_TAINTRETR1,		//4				,2				,retry before fail to initialise								, 	
	SET_TALIMBYP01,		//4				,0 				,consecutive placement down position error before breakdown  ,      
	SET_TALIMPIC01,		//4				,0 				,consecutive picking down position error before breakdown  ,                        
	SET_TAREJDP001,		//4				,32				,down position error unit reject position (0 - 19)	, 
	TEA_TAWORKP201,		//9				,2000			,pick up position(um)    					,
	SET_TAMODGP201,		//4				,250			,gap between module for auto teach pick position(um) 				,

	//MODULE_ID_10 Polarity 
	//SET_POLAYOUT01,		//4			,2			,layout position (0 - 19)                         ,极性测试位置(0 - 19)  
	SET_POFORWARD1,		//4			,0			,forward bias:0)0 1)90 2)-90 3)180 4)-180		        ,极性测试正方旋转 (0=0 1=90 2=-90 3=180 4=-180)
	SET_POREVERSE1,		//4			,3			,reverse bias:0)0 1)90 2)-90 3)180 4 -180		        ,极性测试反方旋转 (0=0 1=90 2=-90 3=180 4=-180)       
	SET_POVOLTAGE1,		//4			,0			,voltage    ,极性测试反方旋转 (0=0 1=90 2=-90 3=180 4=-180)
	SET_POTHRESHO1,		//4			,100		,threshold    ,极性测试反方旋转 (0=0 1=90 2=-90 3=180 4=-180)
	SET_POREJECT01,		//4			,32			,reject position										,极性测试不良位置        
	SET_POLIMBYP01,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_POREJDP001,		//4				,32				,down position error unit reject position (0 - 19)	, 

	//MODULE_ID_11 Checker 1
	SET_CHCONBAD01,		//4				,1				,consecutive bad unit before breakdown(0->Disable)		,
	SET_CHCONLOS01,		//4				,1				,consecutive lost unit before breakdown(0->Disable)		,

	//MODULE_ID_12 Checker 2
	SET_CHCONBAD02,		//4				,1				,consecutive bad unit before breakdown(0->Disable)		,
	SET_CHCONLOS02,		//4				,1				,consecutive lost unit before breakdown(0->Disable)		,

	//MODULE_ID_13 Checker 3
	SET_CHCONBAD03,		//4				,1				,consecutive bad unit before breakdown(0->Disable)		,
	SET_CHCONLOS03,		//4				,1				,consecutive lost unit before breakdown(0->Disable)		,

	//MODULE_ID_14 Test 1
	SET_TESIMULOPT,		//4				,0				,simulation mode:0)Random Fixed)1-10 bin						,
	SET_TESIMULPCT,		//3				,95				,simulation yield(%)											,
	SET_TEGPIBTYPE,		//9				,1				,GPIB type:1)Normal 2)Credence 3)Catalyst 4)J750 5)SR   ,        
	SET_TEGPIBADDR,		//9				,0				,GPIB primary address: 0)Default >1)Customize        ,  
	SET_TEGPIBRTY1,		//4				,3				,GPIB communication retry before breakdown						,
	SET_TEYICOMPA1,		//4				,0				,yield difference comparison mode: 0)disabled 1)warning 2)alarm		,
	SET_TEUNITTES1,		//3				,95				,unit tested before test is valid for comparison		,
	SET_TEYIDIFFE1,		//9				,1				,yield difference threshold(%)     ,        
	SET_TETETOLOW1,		//4				,90				,low yield threshold(%)									,
	SET_TEQAPOS001,		//4				,0				,QA mode assign position							,
	SET_TEBITGOD01,		//2				,1				,good unit result bit										,
	SET_TEB01GOTO1,		//2				,32				,result bit 1 assign position								, 
	SET_TEB02GOTO1,		//2				,32				,result bit 2 assign position								,
	SET_TEB03GOTO1,		//2				,32				,result bit 3 assign position								, 
	SET_TEB04GOTO1,		//2				,32				,result bit 4 assign position								,
	SET_TEB05GOTO1,		//2				,32				,result bit 5 assign position								, 
	SET_TEB06GOTO1,		//2				,32				,result bit 6 assign position								,
	SET_TEB07GOTO1,		//2				,32				,result bit 7 assign position								, 
	SET_TEB08GOTO1,		//2				,32				,result bit 8 assign position								,
	SET_TEB09GOTO1,		//2				,32				,result bit 9 assign position								,
	SET_TEB10GOTO1,		//2				,32				,result bit 10 assign position								,
	SET_TEB11GOTO1,		//2				,32				,result bit 11 assign position								, 
	SET_TEB12GOTO1,		//2				,32				,result bit 12 assign position								,
	SET_TEB13GOTO1,		//2				,32				,result bit 13 assign position								, 
	SET_TEB14GOTO1,		//2				,32				,result bit 14 assign position								,
	SET_TEB15GOTO1,		//2				,32				,result bit 15 assign position								, 
	SET_TEB16GOTO1,		//2				,32				,result bit 16 assign position								,
	SET_TEB17GOTO1,		//2				,32				,result bit 17 assign position								, 
	SET_TEB18GOTO1,		//2				,32				,result bit 18 assign position								,
	SET_TEB19GOTO1,		//2				,32				,result bit 19 assign position								,
	SET_TEB20GOTO1,		//2				,32				,result bit 20 assign position								,
	SET_TEB21GOTO1,		//2				,32				,result bit 21 assign position								,
	SET_TEB22GOTO1,		//2				,32				,result bit 22 assign position								,
	SET_TEB23GOTO1,		//2				,32				,result bit 23 assign position								,
	SET_TEB24GOTO1,		//2				,32				,result bit 24 assign position								,
	SET_TEBITSECH1,		//2				,32				,more than one result bit reject position					,
	SET_TEBITNOS01,		//2				,32				,no result bit reject position								,
	SET_TECONRESU1,		//4				,0				,consecutive test result before breakdown(0->Disable)		,
	SET_TECONFAIL1,		//4				,0				,consecutive fail result before breakdown(0->Disable)		,
	SET_TEPARALLE1,		//4				,0				,parallel group ID (0->Disable)								,
	SET_TELIMBYP01,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_TEREJDP001,		//4				,32				,down position error unit reject position (0 - 19)	, 

	//MODULE_ID_15 Test 2
	SET_TETETOLOW2,		//4				,90				,low yield threshold(%)									,
	SET_TEBITGOD02,		//2				,1				,good unit result bit										,
	SET_TEB01GOTO2,		//2				,32				,result bit 1 assign position								, 
	SET_TEB02GOTO2,		//2				,32				,result bit 2 assign position								,
	SET_TEB03GOTO2,		//2				,32				,result bit 3 assign position								, 
	SET_TEB04GOTO2,		//2				,32				,result bit 4 assign position								,
	SET_TEB05GOTO2,		//2				,32				,result bit 5 assign position								, 
	SET_TEB06GOTO2,		//2				,32				,result bit 6 assign position								,
	SET_TEB07GOTO2,		//2				,32				,result bit 7 assign position								, 
	SET_TEB08GOTO2,		//2				,32				,result bit 8 assign position								,
	SET_TEB09GOTO2,		//2				,32				,result bit 9 assign position								,
	SET_TEB10GOTO2,		//2				,32				,result bit 10 assign position								,
	SET_TEB11GOTO2,		//2				,32				,result bit 11 assign position								, 
	SET_TEB12GOTO2,		//2				,32				,result bit 12 assign position								,
	SET_TEB13GOTO2,		//2				,32				,result bit 13 assign position								, 
	SET_TEB14GOTO2,		//2				,32				,result bit 14 assign position								,
	SET_TEB15GOTO2,		//2				,32				,result bit 15 assign position								, 
	SET_TEB16GOTO2,		//2				,32				,result bit 16 assign position								,
	SET_TEB17GOTO2,		//2				,32				,result bit 17 assign position								, 
	SET_TEB18GOTO2,		//2				,32				,result bit 18 assign position								,
	SET_TEB19GOTO2,		//2				,32				,result bit 19 assign position								,
	SET_TEB20GOTO2,		//2				,32				,result bit 20 assign position								,
	SET_TEB21GOTO2,		//2				,32				,result bit 21 assign position								,
	SET_TEB22GOTO2,		//2				,32				,result bit 22 assign position								,
	SET_TEB23GOTO2,		//2				,32				,result bit 23 assign position								,
	SET_TEB24GOTO2,		//2				,32				,result bit 24 assign position								,
	SET_TEBITSECH2,		//2				,32				,more than one result bit reject position					,
	SET_TEBITNOS02,		//2				,32				,no result bit reject position								,
	SET_TECONRESU2,		//4				,0				,consecutive test result before breakdown(0->Disable)		,
	SET_TECONFAIL2,		//4				,0				,consecutive fail result before breakdown(0->Disable)		,
	SET_TEPARALLE2,		//4				,0				,parallel group ID (0->Disable)								,
	SET_TELIMBYP02,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_TEREJDP002,		//4				,32				,down position error unit reject position (0 - 19)	, 

	//MODULE_ID_16 Test 3
	SET_TETETOLOW3,		//4				,90				,low yield threshold(%)									,
	SET_TEBITGOD03,		//2				,1				,good unit result bit										,
	SET_TEB01GOTO3,		//2				,32				,result bit 1 assign position								, 
	SET_TEB02GOTO3,		//2				,32				,result bit 2 assign position								,
	SET_TEB03GOTO3,		//2				,32				,result bit 3 assign position								, 
	SET_TEB04GOTO3,		//2				,32				,result bit 4 assign position								,
	SET_TEB05GOTO3,		//2				,32				,result bit 5 assign position								, 
	SET_TEB06GOTO3,		//2				,32				,result bit 6 assign position								,
	SET_TEB07GOTO3,		//2				,32				,result bit 7 assign position								, 
	SET_TEB08GOTO3,		//2				,32				,result bit 8 assign position								,
	SET_TEB09GOTO3,		//2				,32				,result bit 9 assign position								,
	SET_TEB10GOTO3,		//2				,32				,result bit 10 assign position								,
	SET_TEB11GOTO3,		//2				,32				,result bit 11 assign position								, 
	SET_TEB12GOTO3,		//2				,32				,result bit 12 assign position								,
	SET_TEB13GOTO3,		//2				,32				,result bit 13 assign position								, 
	SET_TEB14GOTO3,		//2				,32				,result bit 14 assign position								,
	SET_TEB15GOTO3,		//2				,32				,result bit 15 assign position								, 
	SET_TEB16GOTO3,		//2				,32				,result bit 16 assign position								,
	SET_TEB17GOTO3,		//2				,32				,result bit 17 assign position								, 
	SET_TEB18GOTO3,		//2				,32				,result bit 18 assign position								,
	SET_TEB19GOTO3,		//2				,32				,result bit 19 assign position								,
	SET_TEB20GOTO3,		//2				,32				,result bit 20 assign position								,
	SET_TEB21GOTO3,		//2				,32				,result bit 21 assign position								,
	SET_TEB22GOTO3,		//2				,32				,result bit 22 assign position								,
	SET_TEB23GOTO3,		//2				,32				,result bit 23 assign position								,
	SET_TEB24GOTO3,		//2				,32				,result bit 24 assign position								,
	SET_TEBITSECH3,		//2				,32				,more than one result bit reject position					,
	SET_TEBITNOS03,		//2				,32				,no result bit reject position								,
	SET_TECONRESU3,		//4				,0				,consecutive test result before breakdown(0->Disable)		,
	SET_TECONFAIL3,		//4				,0				,consecutive fail result before breakdown(0->Disable)		,
	SET_TEPARALLE3,		//4				,0				,parallel group ID (0->Disable)								,
	SET_TELIMBYP03,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_TEREJDP003,		//4				,32				,down position error unit reject position (0 - 19)	, 

	//MODULE_ID_17 Test 4
	SET_TETETOLOW4,		//4				,90				,low yield threshold(%)									,
	SET_TEBITGOD04,		//2				,1				,good unit result bit										,
	SET_TEB01GOTO4,		//2				,32				,result bit 1 assign position								, 
	SET_TEB02GOTO4,		//2				,32				,result bit 2 assign position								,
	SET_TEB03GOTO4,		//2				,32				,result bit 3 assign position								, 
	SET_TEB04GOTO4,		//2				,32				,result bit 4 assign position								,
	SET_TEB05GOTO4,		//2				,32				,result bit 5 assign position								, 
	SET_TEB06GOTO4,		//2				,32				,result bit 6 assign position								,
	SET_TEB07GOTO4,		//2				,32				,result bit 7 assign position								, 
	SET_TEB08GOTO4,		//2				,32				,result bit 8 assign position								,
	SET_TEB09GOTO4,		//2				,32				,result bit 9 assign position								,
	SET_TEB10GOTO4,		//2				,32				,result bit 10 assign position								,
	SET_TEB11GOTO4,		//2				,32				,result bit 11 assign position								, 
	SET_TEB12GOTO4,		//2				,32				,result bit 12 assign position								,
	SET_TEB13GOTO4,		//2				,32				,result bit 13 assign position								, 
	SET_TEB14GOTO4,		//2				,32				,result bit 14 assign position								,
	SET_TEB15GOTO4,		//2				,32				,result bit 15 assign position								, 
	SET_TEB16GOTO4,		//2				,32				,result bit 16 assign position								,
	SET_TEB17GOTO4,		//2				,32				,result bit 17 assign position								, 
	SET_TEB18GOTO4,		//2				,32				,result bit 18 assign position								,
	SET_TEB19GOTO4,		//2				,32				,result bit 19 assign position								,
	SET_TEB20GOTO4,		//2				,32				,result bit 20 assign position								,
	SET_TEB21GOTO4,		//2				,32				,result bit 21 assign position								,
	SET_TEB22GOTO4,		//2				,32				,result bit 22 assign position								,
	SET_TEB23GOTO4,		//2				,32				,result bit 23 assign position								,
	SET_TEB24GOTO4,		//2				,32				,result bit 24 assign position								,
	SET_TEBITSECH4,		//2				,32				,more than one result bit reject position					,
	SET_TEBITNOS04,		//2				,32				,no result bit reject position								,
	SET_TECONRESU4,		//4				,0				,consecutive test result before breakdown(0->Disable)		,
	SET_TECONFAIL4,		//4				,0				,consecutive fail result before breakdown(0->Disable)		,
	SET_TEPARALLE4,		//4				,0				,parallel group ID (0->Disable)								,
	SET_TELIMBYP04,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_TEREJDP004,		//4				,32				,down position error unit reject position (0 - 19)	, 

	//MODULE_ID_18 Test 5
	SET_TETETOLOW5,		//4				,90				,low yield threshold(%)									,
	SET_TEBITGOD05,		//2				,1				,good unit result bit										,
	SET_TEB01GOTO5,		//2				,32				,result bit 1 assign position								, 
	SET_TEB02GOTO5,		//2				,32				,result bit 2 assign position								,
	SET_TEB03GOTO5,		//2				,32				,result bit 3 assign position								, 
	SET_TEB04GOTO5,		//2				,32				,result bit 4 assign position								,
	SET_TEB05GOTO5,		//2				,32				,result bit 5 assign position								, 
	SET_TEB06GOTO5,		//2				,32				,result bit 6 assign position								,
	SET_TEB07GOTO5,		//2				,32				,result bit 7 assign position								, 
	SET_TEB08GOTO5,		//2				,32				,result bit 8 assign position								,
	SET_TEB09GOTO5,		//2				,32				,result bit 9 assign position								,
	SET_TEB10GOTO5,		//2				,32				,result bit 10 assign position								,
	SET_TEB11GOTO5,		//2				,32				,result bit 11 assign position								, 
	SET_TEB12GOTO5,		//2				,32				,result bit 12 assign position								,
	SET_TEB13GOTO5,		//2				,32				,result bit 13 assign position								, 
	SET_TEB14GOTO5,		//2				,32				,result bit 14 assign position								,
	SET_TEB15GOTO5,		//2				,32				,result bit 15 assign position								, 
	SET_TEB16GOTO5,		//2				,32				,result bit 16 assign position								,
	SET_TEB17GOTO5,		//2				,32				,result bit 17 assign position								, 
	SET_TEB18GOTO5,		//2				,32				,result bit 18 assign position								,
	SET_TEB19GOTO5,		//2				,32				,result bit 19 assign position								,
	SET_TEB20GOTO5,		//2				,32				,result bit 20 assign position								,
	SET_TEB21GOTO5,		//2				,32				,result bit 21 assign position								,
	SET_TEB22GOTO5,		//2				,32				,result bit 22 assign position								,
	SET_TEB23GOTO5,		//2				,32				,result bit 23 assign position								,
	SET_TEB24GOTO5,		//2				,32				,result bit 24 assign position								,
	SET_TEBITSECH5,		//2				,32				,more than one result bit reject position					,
	SET_TEBITNOS05,		//2				,32				,no result bit reject position								,
	SET_TECONRESU5,		//4				,0				,consecutive test result before breakdown(0->Disable)		,
	SET_TECONFAIL5,		//4				,0				,consecutive fail result before breakdown(0->Disable)		,
	SET_TEPARALLE5,		//4				,0				,parallel group ID (0->Disable)								,
	SET_TELIMBYP05,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_TEREJDP005,		//4				,32				,down position error unit reject position (0 - 19)	, 

	//MODULE_ID_19 Test 6
	SET_TETETOLOW6,		//4				,90				,low yield threshold(%)									,
	SET_TEBITGOD06,		//2				,1				,good unit result bit										,
	SET_TEB01GOTO6,		//2				,32				,result bit 1 assign position								, 
	SET_TEB02GOTO6,		//2				,32				,result bit 2 assign position								,
	SET_TEB03GOTO6,		//2				,32				,result bit 3 assign position								, 
	SET_TEB04GOTO6,		//2				,32				,result bit 4 assign position								,
	SET_TEB05GOTO6,		//2				,32				,result bit 5 assign position								, 
	SET_TEB06GOTO6,		//2				,32				,result bit 6 assign position								,
	SET_TEB07GOTO6,		//2				,32				,result bit 7 assign position								, 
	SET_TEB08GOTO6,		//2				,32				,result bit 8 assign position								,
	SET_TEB09GOTO6,		//2				,32				,result bit 9 assign position								,
	SET_TEB10GOTO6,		//2				,32				,result bit 10 assign position								,
	SET_TEB11GOTO6,		//2				,32				,result bit 11 assign position								, 
	SET_TEB12GOTO6,		//2				,32				,result bit 12 assign position								,
	SET_TEB13GOTO6,		//2				,32				,result bit 13 assign position								, 
	SET_TEB14GOTO6,		//2				,32				,result bit 14 assign position								,
	SET_TEB15GOTO6,		//2				,32				,result bit 15 assign position								, 
	SET_TEB16GOTO6,		//2				,32				,result bit 16 assign position								,
	SET_TEB17GOTO6,		//2				,32				,result bit 17 assign position								, 
	SET_TEB18GOTO6,		//2				,32				,result bit 18 assign position								,
	SET_TEB19GOTO6,		//2				,32				,result bit 19 assign position								,
	SET_TEB20GOTO6,		//2				,32				,result bit 20 assign position								,
	SET_TEB21GOTO6,		//2				,32				,result bit 21 assign position								,
	SET_TEB22GOTO6,		//2				,32				,result bit 22 assign position								,
	SET_TEB23GOTO6,		//2				,32				,result bit 23 assign position								,
	SET_TEB24GOTO6,		//2				,32				,result bit 24 assign position								,
	SET_TEBITSECH6,		//2				,32				,more than one result bit reject position					,
	SET_TEBITNOS06,		//2				,32				,no result bit reject position								,
	SET_TECONRESU6,		//4				,0				,consecutive test result before breakdown(0->Disable)		,
	SET_TECONFAIL6,		//4				,0				,consecutive fail result before breakdown(0->Disable)		,
	SET_TEPARALLE6,		//4				,0				,parallel group ID (0->Disable)								,
	SET_TELIMBYP06,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_TEREJDP006,		//4				,32				,down position error unit reject position (0 - 19)	, 

	//MODULE_ID_20 Test 7
	SET_TETETOLOW7,		//4				,90				,low yield threshold(%)									,
	SET_TEBITGOD07,		//2				,1				,good unit result bit										,
	SET_TEB01GOTO7,		//2				,32				,result bit 1 assign position								, 
	SET_TEB02GOTO7,		//2				,32				,result bit 2 assign position								,
	SET_TEB03GOTO7,		//2				,32				,result bit 3 assign position								, 
	SET_TEB04GOTO7,		//2				,32				,result bit 4 assign position								,
	SET_TEB05GOTO7,		//2				,32				,result bit 5 assign position								, 
	SET_TEB06GOTO7,		//2				,32				,result bit 6 assign position								,
	SET_TEB07GOTO7,		//2				,32				,result bit 7 assign position								, 
	SET_TEB08GOTO7,		//2				,32				,result bit 8 assign position								,
	SET_TEB09GOTO7,		//2				,32				,result bit 9 assign position								,
	SET_TEB10GOTO7,		//2				,32				,result bit 10 assign position								,
	SET_TEB11GOTO7,		//2				,32				,result bit 11 assign position								, 
	SET_TEB12GOTO7,		//2				,32				,result bit 12 assign position								,
	SET_TEB13GOTO7,		//2				,32				,result bit 13 assign position								, 
	SET_TEB14GOTO7,		//2				,32				,result bit 14 assign position								,
	SET_TEB15GOTO7,		//2				,32				,result bit 15 assign position								, 
	SET_TEB16GOTO7,		//2				,32				,result bit 16 assign position								,
	SET_TEB17GOTO7,		//2				,32				,result bit 17 assign position								, 
	SET_TEB18GOTO7,		//2				,32				,result bit 18 assign position								,
	SET_TEB19GOTO7,		//2				,32				,result bit 19 assign position								,
	SET_TEB20GOTO7,		//2				,32				,result bit 20 assign position								,
	SET_TEB21GOTO7,		//2				,32				,result bit 21 assign position								,
	SET_TEB22GOTO7,		//2				,32				,result bit 22 assign position								,
	SET_TEB23GOTO7,		//2				,32				,result bit 23 assign position								,
	SET_TEB24GOTO7,		//2				,32				,result bit 24 assign position								,
	SET_TEBITSECH7,		//2				,32				,more than one result bit reject position					,
	SET_TEBITNOS07,		//2				,32				,no result bit reject position								,
	SET_TECONRESU7,		//4				,0				,consecutive test result before breakdown(0->Disable)		,
	SET_TECONFAIL7,		//4				,0				,consecutive fail result before breakdown(0->Disable)		,
	SET_TEPARALLE7,		//4				,0				,parallel group ID (0->Disable)								,
	SET_TELIMBYP07,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_TEREJDP007,		//4				,32				,down position error unit reject position (0 - 19)	, 
	
	//MODULE_ID_21 Test 8
	SET_TETETOLOW8,		//4				,90				,low yield threshold(%)									,
	SET_TEBITGOD08,		//2				,1				,good unit result bit										,
	SET_TEB01GOTO8,		//2				,32				,result bit 1 assign position								, 
	SET_TEB02GOTO8,		//2				,32				,result bit 2 assign position								,
	SET_TEB03GOTO8,		//2				,32				,result bit 3 assign position								, 
	SET_TEB04GOTO8,		//2				,32				,result bit 4 assign position								,
	SET_TEB05GOTO8,		//2				,32				,result bit 5 assign position								, 
	SET_TEB06GOTO8,		//2				,32				,result bit 6 assign position								,
	SET_TEB07GOTO8,		//2				,32				,result bit 7 assign position								, 
	SET_TEB08GOTO8,		//2				,32				,result bit 8 assign position								,
	SET_TEB09GOTO8,		//2				,32				,result bit 9 assign position								,
	SET_TEB10GOTO8,		//2				,32				,result bit 10 assign position								,
	SET_TEB11GOTO8,		//2				,32				,result bit 11 assign position								, 
	SET_TEB12GOTO8,		//2				,32				,result bit 12 assign position								,
	SET_TEB13GOTO8,		//2				,32				,result bit 13 assign position								, 
	SET_TEB14GOTO8,		//2				,32				,result bit 14 assign position								,
	SET_TEB15GOTO8,		//2				,32				,result bit 15 assign position								, 
	SET_TEB16GOTO8,		//2				,32				,result bit 16 assign position								,
	SET_TEB17GOTO8,		//2				,32				,result bit 17 assign position								, 
	SET_TEB18GOTO8,		//2				,32				,result bit 18 assign position								,
	SET_TEB19GOTO8,		//2				,32				,result bit 19 assign position								,
	SET_TEB20GOTO8,		//2				,32				,result bit 20 assign position								,
	SET_TEB21GOTO8,		//2				,32				,result bit 21 assign position								,
	SET_TEB22GOTO8,		//2				,32				,result bit 22 assign position								,
	SET_TEB23GOTO8,		//2				,32				,result bit 23 assign position								,
	SET_TEB24GOTO8,		//2				,32				,result bit 24 assign position								,
	SET_TEBITSECH8,		//2				,32				,more than one result bit reject position					,
	SET_TEBITNOS08,		//2				,32				,no result bit reject position								,
	SET_TECONRESU8,		//4				,0				,consecutive test result before breakdown(0->Disable)		,
	SET_TECONFAIL8,		//4				,0				,consecutive fail result before breakdown(0->Disable)		,
	SET_TEPARALLE8,		//4				,0				,parallel group ID (0->Disable)								,
	SET_TELIMBYP08,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_TEREJDP008,		//4				,32				,down position error unit reject position (0 - 19)	, 
	
	//MODULE_ID_127 Test MEMS 1
	SET_TMSTVELO01,		//4				,90000			,stepper motor velocity										,
	SET_TMSTACCE01,		//4				,90000			,stepper motor acceleration									,
	TEA_TMSOCKPOS1,		//4				,10				,socket at module position											,
	TEA_TMTURRPOS1,		//4				,10				,socket at turret position											,
	SET_TMLIMBYP01,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_TMREJDP001,		//4				,32				,down position error unit reject position (0 - 19)	, 
	SET_TMRETRACT1,		//4				,500			,PUH retract before socket move to module(um)						,

	//MODULE_ID_128 Test MEMS 2
	SET_TMSTVELO02,		//4				,90000			,stepper motor velocity										,
	SET_TMSTACCE02,		//4				,90000			,stepper motor acceleration									,
	TEA_TMSOCKPOS2,		//4				,10				,socket at module position											,
	TEA_TMTURRPOS2,		//4				,10				,socket at turret position											,
	SET_TMLIMBYP02,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_TMREJDP002,		//4				,32				,down position error unit reject position (0 - 19)	, 
	SET_TMRETRACT2,		//4				,500			,PUH retract before socket move to module(um)						,

	//MODULE_ID_129 Test MEMS 3
	SET_TMSTVELO03,		//4				,90000			,stepper motor velocity										,
	SET_TMSTACCE03,		//4				,90000			,stepper motor acceleration									,
	TEA_TMSOCKPOS3,		//4				,10				,socket at module position											,
	TEA_TMTURRPOS3,		//4				,10				,socket at turret position											,
	SET_TMLIMBYP03,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_TMREJDP003,		//4				,32				,down position error unit reject position (0 - 19)	, 
	SET_TMRETRACT3,		//4				,500			,PUH retract before socket move to module(um)						,

	//MODULE_ID_130 Test MEMS 4
	SET_TMSTVELO04,		//4				,90000			,stepper motor velocity										,
	SET_TMSTACCE04,		//4				,90000			,stepper motor acceleration									,
	TEA_TMSOCKPOS4,		//4				,10				,socket at module position											,
	TEA_TMTURRPOS4,		//4				,10				,socket at turret position											,
	SET_TMLIMBYP04,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_TMREJDP004,		//4				,32				,down position error unit reject position (0 - 19)	, 
	SET_TMRETRACT4,		//4				,500			,PUH retract before socket move to module(um)						,

	//MODULE_ID_131 Test MEMS 5
	SET_TMSTVELO05,		//4				,90000			,stepper motor velocity										,
	SET_TMSTACCE05,		//4				,90000			,stepper motor acceleration									,
	TEA_TMSOCKPOS5,		//4				,10				,socket at module position											,
	TEA_TMTURRPOS5,		//4				,10				,socket at turret position											,
	SET_TMLIMBYP05,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_TMREJDP005,		//4				,32				,down position error unit reject position (0 - 19)	, 
	SET_TMRETRACT5,		//4				,500			,PUH retract before socket move to module(um)						,

	//MODULE_ID_132 Test MEMS 6
	SET_TMSTVELO06,		//4				,90000			,stepper motor velocity										,
	SET_TMSTACCE06,		//4				,90000			,stepper motor acceleration									,
	TEA_TMSOCKPOS6,		//4				,10				,socket at module position											,
	TEA_TMTURRPOS6,		//4				,10				,socket at turret position											,
	SET_TMLIMBYP06,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_TMREJDP006,		//4				,32				,down position error unit reject position (0 - 19)	, 
	SET_TMRETRACT6,		//4				,500			,PUH retract before socket move to module(um)						,

	//MODULE_ID_133 Test MEMS 7
	SET_TMSTVELO07,		//4				,90000			,stepper motor velocity										,
	SET_TMSTACCE07,		//4				,90000			,stepper motor acceleration									,
	TEA_TMSOCKPOS7,		//4				,10				,socket at module position											,
	TEA_TMTURRPOS7,		//4				,10				,socket at turret position											,
	SET_TMLIMBYP07,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_TMREJDP007,		//4				,32				,down position error unit reject position (0 - 19)	, 
	SET_TMRETRACT7,		//4				,500			,PUH retract before socket move to module(um)						,

	//MODULE_ID_134 Test MEMS 8
	SET_TMSTVELO08,		//4				,90000			,stepper motor velocity										,
	SET_TMSTACCE08,		//4				,90000			,stepper motor acceleration									,
	TEA_TMSOCKPOS8,		//4				,10				,socket at module position											,
	TEA_TMTURRPOS8,		//4				,10				,socket at turret position											,
	SET_TMLIMBYP08,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_TMREJDP008,		//4				,32				,down position error unit reject position (0 - 19)	, 
	SET_TMRETRACT8,		//4				,500			,PUH retract before socket move to module(um)						,

	//MODULE_ID_22 Tribin 1
	SET_BTCONFUL11,		//4				,0				,consecutive bin 1 full before breakdown(0->Disable)		,
	SET_BTCONFUL21,		//4				,0				,consecutive bin 2 full before breakdown(0->Disable)		,
	SET_BTCONFUL31,		//4				,0				,consecutive bin 3 full before breakdown(0->Disable)		,

	//MODULE_ID_23 Tribin 2
	SET_BTCONFUL12,		//4				,0				,consecutive bin 1 full before breakdown(0->Disable)		,
	SET_BTCONFUL22,		//4				,0				,consecutive bin 2 full before breakdown(0->Disable)		,
	SET_BTCONFUL32,		//4				,0				,consecutive bin 3 full before breakdown(0->Disable)		,

	//MODULE_ID_24 Tribin 3
	SET_BTCONFUL13,		//4				,0				,consecutive bin 1 full before breakdown(0->Disable)		,
	SET_BTCONFUL23,		//4				,0				,consecutive bin 2 full before breakdown(0->Disable)		,
	SET_BTCONFUL33,		//4				,0				,consecutive bin 3 full before breakdown(0->Disable)		,
	
	//MODULE_ID_25 Bin 1
	SET_BUCONFULL1,		//4				,0				,consecutive full before breakdown(0->Disable)		,
	
	//MODULE_ID_26 Bin 2
	SET_BUCONFULL2,		//4				,0				,consecutive full before breakdown(0->Disable)		,
	
	//MODULE_ID_27 Bin 3
	SET_BUCONFULL3,		//4				,0				,consecutive full before breakdown(0->Disable)		,
	
	//MODULE_ID_28 Bin 4
	SET_BUCONFULL4,		//4				,0				,consecutive full before breakdown(0->Disable)		,
	
	//MODULE_ID_29 Bin 5
	SET_BUCONFULL5,		//4				,0				,consecutive full before breakdown(0->Disable)		,
	
	//MODULE_ID_30 Bin 6
	SET_BUCONFULL6,		//4				,0				,consecutive full before breakdown(0->Disable)		,
	
	//MODULE_ID_31 Bin 7
	SET_BUCONFULL7,		//4				,0				,consecutive full before breakdown(0->Disable)		,

	//MODULE_ID_32 Bin 8
	SET_BUCONFULL8,		//4				,0				,consecutive full before breakdown(0->Disable)		,

	//MODULE_ID_33 Bin 9
	SET_BUCONFULL9,		//4				,0				,consecutive full before breakdown(0->Disable)		,

	//MODULE_ID_34 Purge bin 
	SET_BUCONFUL10,		//4				,0				,consecutive full before breakdown(0->Disable)		,

	//MODULE_ID_35 Vision 1
	SET_VISIMULOPT,		//4				,0				,simulation mode:0)Reject 1)Pass 2)Random 3)+90 4)-90		,
	SET_VISIMULPCT,		//3				,95				,simulation yield(%)										,  
	SET_VIVISTYPE1,		//3				,0				,mode:0)Orient 1)Mark 2)Lead 3)Mark_Lead 4)Package			,
	SET_VIPRELOS01,		//4				,1				,consecutive lost unit before breakdown(0->Disable)		, 
	SET_VIREJMARV1,		//3				,13				,reject mark position											,
	SET_VIREJLEAV1,		//3				,13				,reject lead position											,
	SET_VIREJPAKV1,		//3				,32				,reject package position									,
	SET_VICONMARK1,		//3				,3				,consecutive mark fail before breakdown					,
	SET_VILIMBYP01,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_VIREJDP001,		//4				,32				,down position error unit reject position (0 - 19)	, 

	//MODULE_ID_36 Vision 2
	SET_VIVISTYPE2,		//3				,1				,mode:0)Orient 1)Mark 2)Lead 3)Mark_Lead 4)Package			,
	SET_VIPRELOS02,		//4				,1				,consecutive lost unit before breakdown(0->Disable)		,
	SET_VIREJMARV2,		//3				,15				,reject mark position											,
	SET_VIREJLEAV2,		//3				,15				,reject lead position											,
	SET_VIREJPAKV2,		//3				,32				,reject package position									,
	SET_VICONLEAD2,		//3				,3				,consecutive lead fail before breakdown					,
	SET_VILIMBYP02,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_VIREJDP002,		//4				,32				,down position error unit reject position (0 - 19)	, 

	//MODULE_ID_37 Vision 3
	SET_VIVISTYPE3,		//3				,3				,mode:0)Orient 1)Mark 2)Lead 3)Mark_Lead 4)Package			,
	SET_VIPRELOS03,		//4				,1				,consecutive lost unit before breakdown(0->Disable)		,
	SET_VIREJMARV3,		//3				,15				,reject mark position										,
	SET_VIREJLEAV3,		//3				,15				,reject lead position										,
	SET_VIREJPAKV3,		//3				,32				,reject package position									,
	SET_VICONLEAD3,		//3				,3				,consecutive lead fail before breakdown					,
	SET_VILIMBYP03,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_VIREJDP003,		//4				,32				,down position error unit reject position (0 - 19)	, 
	
	//MODULE_ID_38 Vision 1
	SET_VTSIMULOPT,		//4				,0				,simulation mode:0)Reject 1)Pass 2)Random 		,
	SET_VTSIMULPCT,		//3				,95				,simulation yield(%)										,  

	//MODULE_ID_42 Taping 1
	SET_TPTRAILER1,		//1				,50				,trailer length											,
	SET_TPLEEDER01,		//1				,110			,leader length												,
	SET_TPPOSICUT1,		//4				,78				,cutter position											,
	SET_TPPOSSEAL1,		//4				,50				,sealing station position									,
	SET_TPEPCCHK01,		//4				,12				,empty pocket sensor position								,
	SET_TPEPCWIND1,		//4				,20				,window position for empty pocket unit replacement			,
	SET_TPVISIPOS1,		//4				,10				,vision inspection for pocket 1(0-100)						,
	SET_TPVISSEAL1,		//4				,73				,vision post seal pocket 1(0-100)							,
	SET_TPSEALWID1,		//4				,8				,sealing head width										,
	SET_TPUNSEAL01,		//4				,0				,leader unsealed pockets									,
	SET_TPPITCH001,		//2				,1				,index pitch:1)->4mm 2)->8mm 3)->12mm 4)->16mm				,
	SET_TPSHAKEN01,		//4				,1				,number of shake tape front and back						,
	SET_TPB4BRKTP1,		//4				,1				,number of vision re-inspection of before breakdown		,
	TEA_TPSPOWORK1,		//4				,10				,working position(encoder)									,
	SET_TPTESTOFF1,		//4				,17				,tester off position										,
	SET_TPPEELFOR1,		//4				,50				,peel force test length									,
	SET_TPDISTANC1,		//9				,14400			,motor movement distance									,
	SET_TPDURATIO1,		//9				,20				,motor movement duration									,
	SET_TPRETRACT1,		//9				,500			,VC retract distance before index							,
	SET_TPINTRETR1,		//4				,2				,retry before fail to initialise							, 	
	SET_TPLIMBYP01,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_TPREJDP001,		//4				,32				,down position error unit reject position (0 - 19)	, 
	SET_TPACKNOL01,		//4				,0				,number units in reel before ready acknowledgement			,
	SET_TPFULLIND1,		//4				,360000			,full revolution index										,
	SET_TPMODULUS1,		//4				,1080000		,tape modulus												,
	SET_TPFOURMMP1,		//4				,14400			,index pulse for 4mm										,
	SET_TPCONSEP01,		//4				,0				,consecutive empty pocket breakdown					,

	//MODULE_ID_43 Taping 2
	SET_TPTRAILER2,		//1				,50				,trailer length											,
	SET_TPLEEDER02,		//1				,110			,leader length												,
	SET_TPPOSICUT2,		//4				,78				,cutter position											,
	SET_TPPOSSEAL2,		//4				,50				,sealing station position									,
	SET_TPEPCCHK02,		//4				,12				,empty pocket sensor position								,
	SET_TPEPCWIND2,		//4				,20				,window position for empty pocket unit replacement			,
	SET_TPVISIPOS2,		//4				,10				,vision inspection for pocket 1(0-100)						,
	SET_TPVISSEAL2,		//4				,73				,vision post seal pocket 1(0-100)							,
	SET_TPSEALWID2,		//4				,8				,sealing head width										,
	SET_TPUNSEAL02,		//4				,0				,leader unsealed pockets									,
	SET_TPPITCH002,		//2				,1				,index pitch:1)->4mm 2)->8mm 3)->12mm 4)->16mm				,
	SET_TPSHAKEN02,		//4				,1				,number of shake tape front and back						,
	SET_TPB4BRKTP2,		//4				,1				,number of vision re-inspection of before breakdown		,
	TEA_TPSPOWORK2,		//4				,10				,working position(encoder)									,
	SET_TPTESTOFF2,		//4				,17				,tester off position										,
	SET_TPPEELFOR2,		//4				,50				,peel force test length									,
	SET_TPDISTANC2,		//9				,14400			,motor movement distance									,
	SET_TPDURATIO2,		//9				,20				,motor movement duration									,
	SET_TPRETRACT2,		//9				,500			,VC retract distance before index							,
	SET_TPINTRETR2,		//4				,2				,retry before fail to initialise							, 	
	SET_TPLIMBYP02,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_TPREJDP002,		//4				,32				,down position error unit reject position (0 - 19)	, 
	SET_TPACKNOL02,		//4				,0				,number units in reel before ready acknowledgement			,
	SET_TPCONSEP02,		//4				,0				,consecutive empty pocket breakdown					,

	//MODULE_ID_44 Flip Flop
	SET_FFACKNOL11,		//4			,100		,Number units in reel before tape 1 ready acknowledgement  ,黏合站位置
	SET_FFACKNOL21,		//4			,100 		,Number units in reel before tape 2 ready acknowledgement  ,黏合站位置

	//MODULE_ID_45 Laser
	SET_LAMASKID11,		//4			,17			,Unit ID(0 - 19) assigned for laser mask #1                ,雷射位置(0 - 19)       
	SET_LAMASKID21,		//4			,0 			,Unit ID(0 - 19) assigned for laser mask #2                ,雷射位置(0 - 19)       
	SET_LAMASKID31,		//4			,0 			,Unit ID(0 - 19) assigned for laser mask #3                ,雷射位置(0 - 19)       
	SET_LAMASKID41,		//4			,0 			,Unit ID(0 - 19) assigned for laser mask #4                ,雷射位置(0 - 19)       
	SET_LAMASKID51,		//4			,0 			,Unit ID(0 - 19) assigned for laser mask #5                ,雷射位置(0 - 19)       
	SET_LAMASKID61,		//4			,0 			,Unit ID(0 - 19) assigned for laser mask #6                ,雷射位置(0 - 19)       
	SET_LAMASKID71,		//4			,0 			,Unit ID(0 - 19) assigned for laser mask #7                ,雷射位置(0 - 19)       
	SET_LAMASKID81,		//4			,0 			,Unit ID(0 - 19) assigned for laser mask #8                ,雷射位置(0 - 19)       

	//MODULE_ID_46 Tube Input
	SET_ITRETRYCL1,		//1			,0			,retry before clamp breakdown    			    ,
	SET_ITBLOWREV1,		//1			,1			,blow reverse cycles before change tube          ,
	SET_ITLOADCOM1,		//1			,1			,stopper to high level sensor distance(unit)		,
	SET_ITJAMRTRY1,		//4			,1			,jam retry										,

	//MODULE_ID_47 Reject Tube Multiple 1
	TEA_RTRTMPOS11,		//2			,6427			,work position 1											,     
	TEA_RTRTMPOS21,		//2			,19384			,work position 2											,     
	TEA_RTRTMPOS31,		//2			,32603			,work position 3											,     
	TEA_RTRTMPOS41,		//2			,45591			,work position 4											,     
	TEA_RTRTMPOS51,		//2			,58627			,work position 5											,     
	TEA_RTRTMPOS61,		//2			,71776			,work position 6											,     
	TEA_RTRTMPOS71,		//2			,84901			,work position 7											,     
	TEA_RTRTMPOS81,		//2			,98151			,work position 8											,     

	SET_RTMGROUP11,		//2			,0				,tube 1 group ID (0-7)										,     
	SET_RTMGROUP21,		//2			,0				,tube 2 group ID (0-7)										,     
	SET_RTMGROUP31,		//2			,0				,tube 3 group ID (0-7)									    ,     
	SET_RTMGROUP41,		//2			,0				,tube 4 group ID (0-7)										,     
	SET_RTMGROUP51,		//2			,0				,tube 5 group ID (0-7)										,     
	SET_RTMGROUP61,		//2			,0				,tube 6 group ID (0-7)										,     
	SET_RTMGROUP71,		//2			,0				,tube 7 group ID (0-7)										,     
	SET_RTMGROUP81,		//2			,0				,tube 8 group ID (0-7)										,     

	SET_RTGRPFUL11,		//2			,0				,group 0 consecutive full before breakdown (0->Disable)		,     
	SET_RTGRPFUL21,		//2			,0				,group 1 consecutive full before breakdown (0->Disable)		,     
	SET_RTGRPFUL31,		//2			,0				,group 2 consecutive full before breakdown (0->Disable)	    ,     
	SET_RTGRPFUL41,		//2			,0				,group 3 consecutive full before breakdown (0->Disable)		,     
	SET_RTGRPFUL51,		//2			,0				,group 4 consecutive full before breakdown (0->Disable)		,     
	SET_RTGRPFUL61,		//2			,0				,group 5 consecutive full before breakdown (0->Disable)		,     
	SET_RTGRPFUL71,		//2			,0				,group 6 consecutive full before breakdown (0->Disable)		,     
	SET_RTGRPFUL81,		//2			,0				,group 7 consecutive full before breakdown (0->Disable)		,     

	SET_RTPRELOS01,		//4			,1			,checker consecutive lost unit before breakdown(0->Disable) ,
	SET_RTPREBAD01,		//4			,1			,checker consecutive bad unit before breakdown(0->Disable)  ,
	SET_RTDISTANC1,		//9			,180000		,motor movement distance									,
	SET_RTDURATIO1,		//9			,20			,motor movement duration									,
	SET_RTUPLIMIT1,		//9			,0			,motor upper limit											,
	SET_RTLIMBYP01,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_RTREJDP001,		//4				,32				,down position error unit reject position (0 - 19)	, 

	//MODULE_ID_48 Reject Tube Multiple 2
	TEA_RTRTMPOS12,		//2			,6427			,work position 1											,     
	TEA_RTRTMPOS22,		//2			,19384			,work position 2											,     
	TEA_RTRTMPOS32,		//2			,32603			,work position 3											,     
	TEA_RTRTMPOS42,		//2			,45591			,work position 4											,     
	TEA_RTRTMPOS52,		//2			,58627			,work position 5											,     
	TEA_RTRTMPOS62,		//2			,71776			,work position 6											,     
	TEA_RTRTMPOS72,		//2			,84901			,work position 7											,     
	TEA_RTRTMPOS82,		//2			,98151			,work position 8											,     

	SET_RTMGROUP12,		//2			,0				,tube 1 group ID (0-7)										,     
	SET_RTMGROUP22,		//2			,0				,tube 2 group ID (0-7)										,     
	SET_RTMGROUP32,		//2			,0				,tube 3 group ID (0-7)									    ,     
	SET_RTMGROUP42,		//2			,0				,tube 4 group ID (0-7)										,     
	SET_RTMGROUP52,		//2			,0				,tube 5 group ID (0-7)										,     
	SET_RTMGROUP62,		//2			,0				,tube 6 group ID (0-7)										,     
	SET_RTMGROUP72,		//2			,0				,tube 7 group ID (0-7)										,     
	SET_RTMGROUP82,		//2			,0				,tube 8 group ID (0-7)										,     

	SET_RTGRPFUL12,		//2			,0				,group 0 consecutive full before breakdown (0->Disable)		,     
	SET_RTGRPFUL22,		//2			,0				,group 1 consecutive full before breakdown (0->Disable)		,     
	SET_RTGRPFUL32,		//2			,0				,group 2 consecutive full before breakdown (0->Disable)	    ,     
	SET_RTGRPFUL42,		//2			,0				,group 3 consecutive full before breakdown (0->Disable)		,     
	SET_RTGRPFUL52,		//2			,0				,group 4 consecutive full before breakdown (0->Disable)		,     
	SET_RTGRPFUL62,		//2			,0				,group 5 consecutive full before breakdown (0->Disable)		,     
	SET_RTGRPFUL72,		//2			,0				,group 6 consecutive full before breakdown (0->Disable)		,     
	SET_RTGRPFUL82,		//2			,0				,group 7 consecutive full before breakdown (0->Disable)		,     

	SET_RTPRELOS02,		//4			,1			,checker consecutive lost unit before breakdown(0->Disable) ,
	SET_RTPREBAD02,		//4			,1			,checker consecutive bad unit before breakdown(0->Disable)  ,
	SET_RTDISTANC2,		//9			,180000		,motor movement distance									,
	SET_RTDURATIO2,		//9			,20			,motor movement duration									,
	SET_RTUPLIMIT2,		//9			,0			,motor upper limit											,
	SET_RTLIMBYP02,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_RTREJDP002,		//4				,32				,down position error unit reject position (0 - 19)	, 

	//MODULE_ID_49 Tube Output
	SET_OTHIGHLEV1,		//4			,0			,track buffer (during tube changing)			     ,
	SET_OTLIMBYP01,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_OTREJDP001,		//4				,32				,down position error unit reject position (0 - 19)	, 

	//MODULE_ID_51 VA 1
	SET_VASIMULOPT,		//4				,0				,simulation mode:0)Reject 1)Pass 2)Random 3)+90 4)-90		,
	SET_VASIMULPCT,		//3				,95				,simulation yield(%)										,  
	SET_VAVISTYPE1,		//3				,0				,mode:0)Orient 1)Mark 2)Lead 3)Mark_Lead 4)Package			,
	SET_VAPRELOS01,		//4				,1				,consecutive lost unit before breakdown(0->Disable)		, 
	SET_VAREJMARV1,		//3				,13				,reject mark position											,
	SET_VAREJLEAV1,		//3				,13				,reject lead position											,
	SET_VAREJPAKV1,		//3				,32				,reject package position									,
	SET_VACONMARK1,		//3				,3				,consecutive mark fail before breakdown					,
	SET_VALIMBYP01,		//4				,0 				,consecutive down position error before breakdown  ,                        
	SET_VAREJDP001,		//4				,32				,down position error unit reject position (0 - 19)	,

	//MODULE_ID_115 Bin Converter
	SET_BCTARPOS01,		//4				,0				,output medium position									,
};
